name: Deploy to EC2
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the files
      uses: actions/checkout@v3
        
    - name: Create key.pem file
      run: echo "${{secrets.EC2_SSH_KEY}}" > key.pem
    
    - name: Chmod created key.pem file
      run: sudo chmod 400 key.pem
    
    - name: Delete old files with SSH
      run: ssh -i key.pem -o StrictHostKeyChecking=no ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}} "rm -rf bancoImobiliarioBack"
    
    - name: Copy files with SSH
      run: scp -i key.pem -o StrictHostKeyChecking=no -r $GITHUB_WORKSPACE ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}}:/home/${{secrets.REMOTE_USER}}
        
    - name: Run API
      run: ssh -i key.pem -o StrictHostKeyChecking=no ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}} "cp .env bancoImobiliarioBack/; cd bancoImobiliarioBack; yarn; sudo systemctl restart lopoly"
